server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://120.24.1.46:3306/footprint?useUnicode=true&characterEncoding=UTF-8
    username: footprint
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

endpoints:
  enabled: false
logging:
  file: ./FootPrint.log
---
spring:
  profiles: dev
  jpa:
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://120.24.1.46:3306/footprint?useUnicode=true&characterEncoding=UTF-8
endpoints:
  enabled: true
---
OSS:
  host: http://foot-print.oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAICVi17CxDTwVT
  accessKeySecret: qvxT2MOKjes09N9pwMWMYlkClwcDwk
  bucketName: foot-print
  endpoint: oss-cn-shanghai.aliyuncs.com
---
emotion:
  token1: aa04808f99754e89b42bb72da5965dfc
  token2: 0cf0a055b47641a597352c2d961e4c95
  api: https://westus.api.cognitive.microsoft.com/emotion/v1.0/recognize